index.php
scripts/blazingkevin.js

Included email as part of the required detail as a result of the update from xyluz.

included email

---

scripts/okeyhacker.js

This is my task okeyhacker HNG-04017

okeyhacker HNG-04017

---

scripts/psalmzcode-HNG-02473.js

well done team titans , great work

psalmzcode-HNG-02743: this is my script

---

scripts/chisomintern.php

chisom-HNG-01667 script

---

scripts/ochuba_Samuel.js
scripts/tmayor.js

created a scripts file that ouputs my details to the console.

Ochuba Samuel  STAGE_2 COMMIT

---

scripts/femakin.js

femakin-HNG-00612 script

---

scripts/muhdmalcolmx.js

Done! Added my script for stage 2

Adding muhdmalcolmx's script for stage 2

---

scripts/liimmaa.js

For liimmaa HNG

---

scripts/silanka.js

A javascript file containing my contribution to the hng stage 2 task

addition of silanka.js file to the script files

---

scripts/BigBello.py

BigBello's script

---

scripts/GraceBabirye.js

approve my pull request thanks

Grace Babirye's task 2

---

scripts/Archit.js

Added Archit.js

---

scripts/ab3id.php

Added new ab3id.php on the script folder

Added Ab3id.php 

---

scripts/tamsay.js

Hello, kindly review and approve my request. It passed the required test. Thank you

tamsay stage 2 solution

---

scripts/adegoke.js

added adegoke.js to the script folder

hng task 2

---

scripts/afaraitsulaimon-hng-01150.php

Here is my updated task, i had to pull back when the update of email came back,so i have made the corrections and i have pushed back and for the first branch i pushed which is **firstPeenarzTeamTask**
Please king ignore it and merge this branch called **peenarzUpdatedTask**

MY UPDATED TASK

---

scripts/halukfurkankicik-03946-JavaScript.js

Testing is succeed. Here is the snippet of output:
{"file":"halukfurkankicik-03946-JavaScript.js","output":"Hello World, this is Haluk Furkan KICIK with HNGi7 ID HNG-03946 and email f.halukkicik@gmail.com using JavaScript for stage 2 task","name":" Haluk Furkan KICIK ","id":" HNG-03946 ","email":" f.halukkicik@gmail.com ","language":" JavaScript ","status":"pass"},

kicikhaluk - HNG-03946 script

---

scripts/Samira.py

Please review and let me know if they are any errors.

Added a script called Samira.py

---

scripts/Olaiya_Ifedapo_Princewill-HNG-03278-Python.py

This is my submission for the task

Princewill(HNG-03278) task 2

---

scripts/tonymj.py

task 2 tony

---

scripts/Diderique.js

Kouokam Fogang Franck Diderique Stage_2

---

scripts/Abdussami_Giwa-HNG-03734-nodejs.js

Abdussami_Giwa-HNG-03734-nodejs

---

lawrecks.js
scripts/ugochukwuEjiogu.js

Please check my script for confirmation

Script for Ugochukwu Ejiogu (Lawrecks)

---

scripts/NEOBOT.py

Tested with XAMPP and it worked fine

Added NEOBOT script file for task 2

---

scripts/oluwashane.js

oluwashane(HNG-01616) task 2

---

scripts/jobafash.js

Added a few unique desc to the task

Changes made to the file

---

scripts/A2348123035681_hgn-01937_php.php

A2348123035681 stage_2 commit

---

scripts/Tabby.js

Added Tabby.js

---

scripts/tenotea.js

The test passed and ready for submission.

Intern Tenotea js script added

---

scripts/webkidt-HNG-05825.js

Pull Request for Task 2 from David Pam HNG-05825

webkidt-HNG-05825 script

---

scripts/Iliasu_Adamu_HNG-o1170.js

Iliasu Adamu HNG-01170 stage_2 commit

---

scripts/adesire.js
scripts/adesire_HNG-01764_javascript.js

Adesire stage2 commit

---

scripts/Odinaka007.py

EMMANUEL_ODINAKA STAGE_2 COMMIT

---

scripts/Iyke.py

Task 2 Script

---

scripts/ablefield.py

Would appreciate if feedbacks are given regarding my submission if it has passed or failed because I do not know how to test run this code on a server but very confident it would run.

ablefield task 2

---

scripts/femithz.js

Femithz added is own script for task 2

Femithz added is own script for task 2

---

scripts/ezeugoFelistusObieze_HNG-03054_js.js

Hello, this is Ezeugo Felistus Obieze; HNG-03054

ezeugoFelistusObieze stage_2 commit

---

scripts/app.js

Hello. This is Afolabi Seyi Samson, term-titians

task Completed

---

scripts/Biggaji.js

Am done with task 2, thank God and friends

Task 2 resolved

---

scripts/debugger.js

This is a pull request to add my script to script folder.

my to be tested script

---

scripts/bosun HNGi7 id_ HNG-00981.py

I've written the code in python.

Bosun HNGi7 id: HNG-00981 stage 2 task

---

scripts/mano.js

push request

---

scripts/Mhista_Gnius.js

'mhista_genius

---

scripts/mikkymillion.php

this is my commit

---

scripts/Sheye.js

Updated sheye.js ( fixed the status "failed" )

---

scripts/tenotea.js

I'm sorry, I sent an incorrect code. Kindly assist in over writing it with this file. Really sorry for any inconvenience I may be posing.

Corrected Script by Intern Tenotea

---

scripts/EmiliaAnoch.js

I have written my script using javascript and tested using Xammp before raising this PR.

feat: Script commit by Emilia

---

scripts/binary.py

Adding Binary Solution to Repo

---

scripts/charley.py

added charley.py to script folder

---

scripts/jimoh_babatunde_intern.php

Jimoh Babatunde

---

scripts/Olaiya.js

Olaiya Stage 2 Commit

---

ifeoluwa.js

ifeoluwa HNG-00042

---

scripts/jamezo.js

jamezo commit

---

scripts/the_Phoenix-HNG-04459.py

I just finished my code and would like it to be accepted. Done with the task!

the_Phoenix HNG-04495 Stage 2 script

---

scripts/iMhyke.js

Michael Madumere Task commit

---

scripts/Iliasu_Adamu_HNG-o1170.js

Revert "Iliasu Adamu HNG-01170 stage_2 commit"

---

Beatrice.py

Reverts team-titians/HNGi7_Titans_Task2#205

Revert "Create Beatrice.py"

---

scripts/CHIBUZO_EBUBECHI_MIRACLE-HNGID_00569-PHP.php

Reverts team-titians/HNGi7_Titans_Task2#111

Revert "CHIBUZO_EBUBECHI_MIRACLE STAGE_2 COMMIT"

---

scripts/ziv.py

Anna Magoma stage 2 commit

---

scripts/SirRoteh.js

Please merge from SirRoteh, Rotimi Adesina for task 2

Rotimi Adesina HNG-02480 SirRoteh Script file

---

index.php
scripts/lihin.js

Lihin Ogana_HNG-00423 stage 2 commit

---

scripts/kdavis.php

Done with task and am submitting script

Adding script for stage 2

---

scripts/olaide.js

olaidedotjs added

---

.gitignore
scripts/dharmyx.js

Added My Script.js file

---

scripts/bkm.py

here is my script for team titans.

bkm scripts

---

scripts/Kodian_kodes.py

@kodian_kodes

---

scripts/Vicman.js

Please merge my codes. Thank you

Added my own file named Vicman.js

---

scripts/shubham.js

adding my contribution to the project.
Slack username: shubham 
Internship ID: HNG-00111

adding shubham.js HNG ID: HNG-00111

---

scripts/Akindeji.js

I just added my javascript file to the script folder. I have tested it, it works

Added my js script file

---

scripts/ujez.js

Greetings to all Titans putting their efforts towards the progress of this team as a whole.

ALIU_ISAAC STAGE_2 COMMIT

---

scripts/bosun.py

This is the remake of the previous one that didn't run

Bosun 2nd task

---

scripts/peterolu.js

Tested and added my js script to the scripts folder

Team member script

---

scripts/shina.js

I have added my script after testing thoroughly. Please do merge it after confirmation.

shina task 2

---

scripts/Ataman.py

add Ataman.py

---

scripts/dflat.php

dflat requests to create pull request

dflat-HNG-03063

---

scripts/eltana.js

Added Eltana script

---

scripts/alvinuchenna.js

Created a Javascript file to be included in the script folder

added my script to the script folder

---

scripts/sjekpo.js

task completed using javascript

---

scripts/OSAKKPOLOR_TOLULOPE_OBASEKI-HNG-01828-JAVASCRIPT.js

Osakpolor_Tolulope_Obaseki STAGE_2 COMMIT

---

scripts/kelvinakpobome.php

Commiting my files

---

scripts/isaac.js

initial commit

---

scripts/vincent_chukwu_hng-00544_javascript.js

Add files via upload for vinn547

---

scripts/MamboBryan.py

Brian Odhiambo STAGE_2 COMMIT

---

scripts/Judith001.js

changed language used from node.js to javascript.

code-refactoring

---

scripts/deejay.js

pls merge my pull request, thanks

Tosin task 2 commit

---

scripts/adedolapo_io.py

script failed previously and would like to recommit.

delete old commit

---

scripts/Shaydee_Coder.js

My script is not listed among the scripts tested on the browser but my codes are fine and the sentence case is fine too. I hope somebody understands what I'm experiencing, this is the best possible way I could the describe it.

Added Shaydee_Coder.js to scripts

---

mykaelson.py

Adebayo Michael with HNG ID HNG-03633 opening a pull request.

Mykaelson.py

---

mykaelson.py

Reverts team-titians/HNGi7_Titans_Task2#324

Revert "Mykaelson.py"

---

index.php

Removed white spaces from json output on the index.php file

Removed whitespaces on json putput

---

scripts/boniface.py

Team task 2

---

scripts/Ajose.js

Kindly review and receive my PR

adding Ajose.js to script folder

---

scripts/rapixar.php

Reverts team-titians/HNGi7_Titans_Task2#23

Revert "Stage 2 task with PHP by rapixar"

---

scripts/bosun.py

Bosun 2nd task correction

---

scripts/FuadGbadamosi.py

Fuad Gbadamosi added a new script

New File added

---

scripts/presydon.js

New commit made and presydon.js was added, awaiting to be merged to the teams project.

Preydon.js was added to the scripts folder

---

scripts/Mykaelson.py

Please I need a revert if I've done it correctly this time.

Adding file to script folder

---

scripts/bosun.py

Bosun correction

---

scripts/victoria.js

Removed full stop at the end of my code.

victoria.js

---

scripts/chinedu_HNG_04341_python.py
scripts/hck3rr.js

Chinedu_Task 2 completed

---

scripts/patrickasu.php

My First HNG7 Task

---

scripts/bosun.py

Another correction again

---

scripts/bosun.py

Another correction

---

scripts/thelma.js

task2 with team titans in HNGi7

---

scripts/HNG-00155.js

Here is my git task2. Thank you.

danielekanim-HNG-00155 script

---

scripts/chimdi.js

hello, my name is Chimdi Nwawueze, Task one for Team_Titans  on HNGi7. 
slack username: @chimdi

 Task2 completed

---

scripts/phirmware.js

my js script

---

scripts/eltana-HNG-01393.js

adding eltana-HNG-01393.js

---

scripts/RandyWuchi.js

adding RandyWuchi.js script to teams repo

---

scripts/Rexford.py

Script added by Rexford

---

scripts/ugochukwuEjiogu.js

I removed the commas in my output

Updated my output

---

scripts/temi_05891.js
scripts/temitope_05891.php

Temitope Hng intern

---

scripts/Dennis.js

created dennis.js

---

scripts/manny.js

Added my script using JavaScript language.
Script name is manny.js

Mnanny added his passed script

---

scripts/HNG-02300.php

Simple PHP CODE TO Print name,email,HNGI7 ID,HELLO WORLD

Ibinabo HNGi7 Stage 2 task

---

scripts/MELODY.py

``def Hng_task():
name= 'Melody'
id='Hngi7-id:HNG-00637'
Email='email-melody.carter43@gmail.com'
language='python'
print ('hello world, this is  {} with {} and {} using {} stage 2 task_'.format(name,id, Email,language))

 MELODY NWUDE.py

---

scripts/olaide.js

I am sure and hopeful this one passes the test

new olaide1.js file

---

scripts/Rexford.py

Script updated due to python version problems

script updated

---

scripts/Muyiwa.py

Muyiwa Script

---

scripts/Adebiyi_sefiyat_HNG-02929_JS.js

ADEBIYI_SEFIYAT_ODUNOLA STAGE_2 COMMIT

---

scripts/Sirri.py

This is is a new pull request to correct changes made before. hopefully.

Sirri raising another pull request

---

scripts/Sirri.py

This is is a new pull request to correct changes made before. hopefully.

updated fork, and Sirr.py

---

scripts/hng_intern_tomi.py

Used __main__ function

---

scripts/Damflex.js

I have added my Javascript. i just did this morning, kindly merge

added my script Damflex.js

---

scripts/orbit.js

orbit tested script

---

scripts/vincentchukwucommitUpdated.js

I skipped a letter in my name on my previous commit.

Final Corrected Commit from vinn547

---

scripts/ujez.js

yet another commit

---

scripts/DIVINE_IKEJIAKU-HNG-05205-PYTHON.py

Merge from original repo to update my forked repo

Merge from original repo

---

scripts/MELODY NWUDE2.py

``def Hng_task():
name= 'Melody Nwude'
id='HNG-00637'
Email='melody.carter43@gmail.com'
language='python'
print ('hello world, this is  {} with {} and {} using {} stage 2 task_'.format(name,id, Email,language))

Update and rename MELODYNWUDE.py to MELODY NWUDE2.py

---

scripts/august.js

Daniel Bemsen Stage 2 commit

---

scripts/the_Phoenix-HNGi7-04459.py

This is my second script. i hope it passes.

the_Phoenix Adding an Updated script now

---

scripts/paschal.js

Created paschal.js

---

scripts/josephcoleshowers.js

added josephcoleshowers.js file

---

scripts/tolz.js

-Write my stage 2 Task in JS
- Added my stage 2 Task

Tolz(03503) stage 2 Task

---

scripts/Toliimaa_HNGi7_Task2.py

Signed-off-by: Toliimaa <tolhassan@gmail.com>

Task2: Introuction

---

scripts/tobiaj.py

tobiaj-HNG-03302 script

---

scripts/nnnamdi.js

Please kindly consider merging my solution to stage1 task

Add the solution to stage1 task

---

scripts/Naimah.js

Add file from Naimat Oyewale

---

scripts/allbright.py

added my stage 2 task python file.

Added my stage2 task

---

scripts/dickachi.php

Task 2 completed

---

scripts/liimmaa.js

Add liimmaa

---

scripts/busuyem.php

Kindly merge my Script to the main repo.
Thanks.

Commit from Owoyemi

---

scripts/Sirri.py

This is is a new pull request to correct changes made before. hopefully.

updated Sirri.py

---

scripts/kolikay.py

created my script

---

Script/huzaius.py
scripts/Abu_Huzaifa-HNG_02607.py

Please accept my task 2 request. Forgot to send the pull request earlier.

Abu_Huzaifa Task 2

---

scripts/orbit.js

I make a correction to my changes

correction of world to World

---

scripts/Akinola-oladayo.js

Oladayo's script

---

scripts/annonbytes.js

Proposed change to add email to script

---

scripts/adedolapo_io.py

Pls delete last commit. Just realized the error was coming from "ID".

adedolapo_io final final

---

scripts/lihin.js

Lihin ogana hng00423

---

scripts/qudusAbolore.js

uploading my task script

---

scripts/oseniifeoluwa.php

My name is OSENI Ifeoluwa Daniel

Here is my source code for task 2 for team titan.

---

scripts/berry-HNG-01620.php

Please this is my final commit help me merge it.

new changes made to my script

---

scripts/iCode.py

Team Task for stage 2

---

scripts/busuyem.php

This correct is made so that my code can pass the test. Kindly merge my correction.
Username: Busuyem

Correction made

---

scripts/the_Phoenix-HNGi7-04459.py

Please if merging is still on... I will appreciate the help.

Delete old and add new submission

---

scripts/peterEse.js

Peter Esekhaigbe stage 2 commit.

Peter Esekhaigbe stage 2 commit.

---

chi-design. js
scripts/chi-design. js

chi-design/HNG-03289 pull request

Pull request for Task 2

---

scripts/joelehis.js

Ehis Script

---

scripts/kayzmann.js
scripts/kayzmann.py

MY Javascript Details

---

scripts/MELODY NWUDE2.py

Update MELODY NWUDE27.py

---

scripts/Abu_Huzaifa-HNG_02607.py

Made corrections. on the task 2

Aligning print statement 

---

scripts/O'Herbert.js

Added my script for task 2

---

scripts/kayzmann.js

new pull request

---

scripts/kayzmann.js

Reverts team-titians/HNGi7_Titans_Task2#666

Revert "new pull request"

---

scripts/charleyvibez.py

added charleyvibez.py

---

scripts/Adebiyi_sefiyat_HNG-02929_JS.js
scripts/odun.js

i have corrected the script please merge it.

correct made

---

scripts/berry-HNG-01620.php

new changes to my script

---

scripts/CORRECTED_BY-CHIBUZO_EBUBECHI-HNGID_00569-PHP.php

Reverts team-titians/HNGi7_Titans_Task2#199

Revert "UPDATE PLEASE STAGE_2"

---

scripts/tonymj.py

please i omited HNGi7 in my script

omited HNGi7

---

scripts/Peteru.js

I did the necessary corrections

corrected my script

---

Scripts/usableCoder.js

Completed my script, please verify and approve.

Dosunmu AbdulRahmon - Team-Titans

---

scripts/Maazi0x3a21b1af-HNG-01419.js

Maazi0x3a21b1af-HNG-01419

---

scripts/BISOLA-HNG-02218-JavaScript.js

committed file

---

scripts/Toniloba.js

I have made commited another file, so this one is no longer needed

Deleting duplicate file

---

scripts/dawillzy.py

Update one last time hopefully

---

scripts/berry-HNG-01620.php

help me merge before last promotion

changed my email

---

scripts/main_03207.js

i have remove the email on this task for stage 2

Corrected 03207,js

---

scripts/Edwards014.js
scripts/Edwards2014.js

sorry, i got my slack username wrong, i had to change it

change file name

---

scripts/ishaku.js

original_ishaku.js

---

scripts/Bryce.js

Created Javascript file for my ID

Creating Java script file for my ID

---

scripts/busuyem.php

another commit

---

scripts/berry-HNG-01620.php

i rearranged my name

---

scripts/sage16.js

Initial push to github

---

scripts/Rufaikudus.js

 Rufai stage 2 task

---

scripts/busuyem.php

Last commit

---

scripts/quillz.php

quillz.php
